### PR TITLE
Update Portuguese - Brasil

### PR DESCRIPTION
**Pull request by LouisUnnoficial**

### CODE REVIEW

**Comment by zo-shin** [comment]
If you want to change something, do that after my request is merged. There is something wrong with yours: you didn’t delete the old folder.

**Comment by LouisUnnoficial** [comment]
@zo-shin 

if the old folder you refer to is values-pt this is from Portugal, mine is Brazilian Portuguese there is a difference in the language.

**Comment by zo-shin** [comment]
OK, I'll rename it after your request.

**Comment by tuyafeng** [comment]
Thanks!

**Pull request merged**
